name: Metrics
on:
  schedule:
    - cron: "0 12 * * *"
  push:
    branches:
      - master
      - main
  workflow_dispatch:
jobs:
  github-metrics-personal:
    runs-on: ubuntu-latest
    steps:
      - name: Left
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: left.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, metadata
          base_indepth: yes
          config_order: base.header, isocalendar, habits
          output_action: gist
          committer_gist: ${{ secrets.GIST }}
          plugin_isocalendar: yes
          plugin_habits: yes
          plugin_habits_from: 1000
          plugin_habits_days: 30
          plugin_habits_charts: yes
          plugin_habits_charts_type: classic
      
      - name: Right
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: right.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          base_indepth: yes
          config_order: languages, wakatime
          output_action: gist
          committer_gist: ${{ secrets.GIST }}
          plugin_languages: yes
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_sections: most-used, recently-used
          plugin_languages_indepth: yes
          plugin_languages_ignored: Hack gitignore
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          plugin_wakatime_days: 30
          plugin_wakatime_languages_ignored: Binary, gitignore
          plugin_wakatime_repositories_visibility: public
